# Generated by Django 5.2.8 on 2025-11-21 13:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.IntegerField(choices=[(1, 'First Chief'), (2, 'Second Chief'), (3, 'Third Chief'), (4, 'Fourth Chief'), (5, 'Fifth Chief')], unique=True)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('death_year', models.IntegerField(blank=True, null=True)),
                ('reign_start', models.IntegerField()),
                ('reign_end', models.IntegerField(blank=True, null=True)),
                ('biography', models.TextField()),
                ('achievements', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='chiefs/')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Chiefs',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('product_type', models.CharField(choices=[('nft', 'NFT'), ('physical', 'Physical Product'), ('both', 'Both NFT & Physical')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('starting_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('bidding', 'Open for Bidding'), ('reserved', 'Reserved')], default='available', max_length=20)),
                ('artist_name', models.CharField(max_length=200)),
                ('dimensions', models.CharField(blank=True, max_length=100)),
                ('materials', models.CharField(blank=True, max_length=200)),
                ('year_created', models.IntegerField(blank=True, null=True)),
                ('stock_quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('featured', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='products/')),
                ('gallery_images', models.JSONField(blank=True, default=list)),
                ('nft_metadata', models.JSONField(blank=True, default=dict, help_text='NFT specific metadata')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon class name', max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Project Categories',
            },
        ),
        migrations.CreateModel(
            name='TourismSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('site_type', models.CharField(choices=[('museum', 'Museum'), ('game_reserve', 'Game Reserve'), ('cultural_site', 'Cultural Site'), ('historical_site', 'Historical Site')], max_length=20)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=300)),
                ('region', models.CharField(default='Southern Highlands', max_length=100)),
                ('opening_hours', models.CharField(max_length=200)),
                ('entry_fee_local', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entry_fee_foreign', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity', models.IntegerField(help_text='Maximum visitors per day')),
                ('amenities', models.TextField(help_text='Available facilities and services')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tourism/')),
                ('gallery_images', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='historical/')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chief', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.chief')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidder_name', models.CharField(max_length=200)),
                ('bidder_email', models.EmailField(max_length=254)),
                ('bidder_phone', models.CharField(max_length=20)),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_winning', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='core.product')),
            ],
            options={
                'ordering': ['-bid_amount', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.productcategory'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('objectives', models.TextField()),
                ('location', models.CharField(max_length=300)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('suspended', 'Suspended')], default='planning', max_length=20)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('beneficiaries', models.IntegerField(help_text='Number of people benefiting')),
                ('progress_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('impact_summary', models.TextField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='projects/')),
                ('gallery_images', models.JSONField(blank=True, default=list)),
                ('partners', models.TextField(blank=True, help_text='Partner organizations')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.projectcategory')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=200)),
                ('visitor_email', models.EmailField(max_length=254)),
                ('visitor_phone', models.CharField(max_length=20)),
                ('visitor_type', models.CharField(choices=[('local', 'Local'), ('foreign', 'Foreign')], max_length=20)),
                ('number_of_visitors', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('visit_date', models.DateField()),
                ('visit_time', models.TimeField()),
                ('special_requirements', models.TextField(blank=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('booking_reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tourism_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.tourismsite')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
